function creatPrototxt(w,h,fileName)
    fp = fopen(fileName, 'w');
    
    fprintf(fp, 'force_backward: 1\n');
    fprintf(fp, '\n');
    
    fprintf(fp, 'layer {\n');
    fprintf(fp, '  name: \"data\"\n');
    fprintf(fp, '  type: \"Input\"\n');
    fprintf(fp, '  top: \"dx\"\n');
    fprintf(fp, '  top: \"dy\"\n');
    fprintf(fp, '  input_param {\n');
    fprintf(fp, '    shape: {dim: %d dim: %d dim: %d dim: %d}\n', 1, 1, w, h);
    fprintf(fp, '    shape: {dim: %d dim: %d dim: %d dim: %d}\n', 1, 1, h, w);
    fprintf(fp, '  }\n');
    fprintf(fp, '}\n');
    fprintf(fp, '\n');
    
    fprintf(fp, '################## grad x\n');
    
    fprintf(fp, 'layer {\n');
    fprintf(fp, '  name: \"conv1_x\"\n');
    fprintf(fp, '  type: \"Convolution\"\n');
    fprintf(fp, '  bottom: \"dx\"\n');
    fprintf(fp, '  top: \"conv1_x\"\n');
    fprintf(fp, '  param {\n');
    fprintf(fp, '    name: \"conv1_f\"\n');
    fprintf(fp, '    lr_mult: 1\n');
    fprintf(fp, '    decay_mult: 1\n');
    fprintf(fp, '  }\n');
    fprintf(fp, '  param {\n');
    fprintf(fp, '    name: \"conv1_b\"\n');
    fprintf(fp, '    lr_mult: 2\n');
    fprintf(fp, '    decay_mult: 1\n');
    fprintf(fp, '  }\n');
    fprintf(fp, '  convolution_param {\n');
    fprintf(fp, '    num_output: %d\n', 64);
    fprintf(fp, '    kernel_size: %d\n', 9);
    fprintf(fp, '    stride: %d\n', 1);
    fprintf(fp, '    group : %d\n', 1);
    fprintf(fp, '    pad: %d\n', 4);
    fprintf(fp, '    weight_filler {\n');
    fprintf(fp, '      type: \"xavier\"\n');
    fprintf(fp, '    }\n');
    fprintf(fp, '    bias_filler {\n');
    fprintf(fp, '      type: \"constant\"\n');
    fprintf(fp, '      value: 0\n');
    fprintf(fp, '    }\n');
    fprintf(fp, '  }\n');
    fprintf(fp, '}\n');
    
    fprintf(fp, 'layer {\n');
    fprintf(fp, '  name: \"relu1_x\"\n');
    fprintf(fp, '  type: \"ReLU\"\n');
    fprintf(fp, '  bottom: \"conv1_x\"\n');
    fprintf(fp, '  top: \"conv1_x\"\n');
    fprintf(fp, '  relu_param{\n');
    fprintf(fp, '    negative_slope: %f\n', 0.1);
    fprintf(fp, '  }\n');
    fprintf(fp, '}\n');
    
    fprintf(fp, 'layer {\n');
    fprintf(fp, '  name: \"conv2_x\"\n');
    fprintf(fp, '  type: \"Convolution\"\n');
    fprintf(fp, '  bottom: \"conv1_x\"\n');
    fprintf(fp, '  top: \"conv2_x\"\n');
    fprintf(fp, '  param {\n');
    fprintf(fp, '    name: \"conv2_f\"\n');
    fprintf(fp, '    lr_mult: 1\n');
    fprintf(fp, '    decay_mult: 1\n');
    fprintf(fp, '  }\n');
    fprintf(fp, '  param {\n');
    fprintf(fp, '    name: \"conv2_b\"\n');
    fprintf(fp, '    lr_mult: 2\n');
    fprintf(fp, '    decay_mult: 1\n');
    fprintf(fp, '  }\n');
    fprintf(fp, '  convolution_param {\n');
    fprintf(fp, '    num_output: %d\n', 128);
    fprintf(fp, '    kernel_size: %d\n', 3);
    fprintf(fp, '    stride: %d\n', 2);
    fprintf(fp, '    group : %d\n', 1);
    fprintf(fp, '    pad: %d\n', 1);
    fprintf(fp, '    weight_filler {\n');
    fprintf(fp, '      type: \"xavier\"\n');
    fprintf(fp, '    }\n');
    fprintf(fp, '    bias_filler {\n');
    fprintf(fp, '      type: \"constant\"\n');
    fprintf(fp, '      value: 0\n');
    fprintf(fp, '    }\n');
    fprintf(fp, '  }\n');
    fprintf(fp, '}\n');
    
    fprintf(fp, 'layer {\n');
    fprintf(fp, '  name: \"relu2_x\"\n');
    fprintf(fp, '  type: \"ReLU\"\n');
    fprintf(fp, '  bottom: \"conv2_x\"\n');
    fprintf(fp, '  top: \"conv2_x\"\n');
    fprintf(fp, '  relu_param{\n');
    fprintf(fp, '    negative_slope: %f\n', 0.1);
    fprintf(fp, '  }\n');
    fprintf(fp, '}\n');
    
    fprintf(fp, 'layer {\n');
    fprintf(fp, '  name: \"conv3_x\"\n');
    fprintf(fp, '  type: \"Convolution\"\n');
    fprintf(fp, '  bottom: \"conv2_x\"\n');
    fprintf(fp, '  top: \"conv3_x\"\n');
    fprintf(fp, '  param {\n');
    fprintf(fp, '    name: \"conv3_f\"\n');
    fprintf(fp, '    lr_mult: 1\n');
    fprintf(fp, '    decay_mult: 1\n');
    fprintf(fp, '  }\n');
    fprintf(fp, '  param {\n');
    fprintf(fp, '    name: \"conv3_b\"\n');
    fprintf(fp, '    lr_mult: 2\n');
    fprintf(fp, '    decay_mult: 1\n');
    fprintf(fp, '  }\n');
    fprintf(fp, '  convolution_param {\n');
    fprintf(fp, '    num_output: %d\n', 128);
    fprintf(fp, '    kernel_size: %d\n', 3);
    fprintf(fp, '    stride: %d\n', 1);
    fprintf(fp, '    group : %d\n', 1);
    fprintf(fp, '    pad: %d\n', 1);
    fprintf(fp, '    weight_filler {\n');
    fprintf(fp, '      type: \"xavier\"\n');
    fprintf(fp, '    }\n');
    fprintf(fp, '    bias_filler {\n');
    fprintf(fp, '      type: \"constant\"\n');
    fprintf(fp, '      value: 0\n');
    fprintf(fp, '    }\n');
    fprintf(fp, '  }\n');
    fprintf(fp, '}\n');
    
    fprintf(fp, 'layer {\n');
    fprintf(fp, '  name: \"relu3_x\"\n');
    fprintf(fp, '  type: \"ReLU\"\n');
    fprintf(fp, '  bottom: \"conv3_x\"\n');
    fprintf(fp, '  top: \"conv3_x\"\n');
    fprintf(fp, '  relu_param{\n');
    fprintf(fp, '    negative_slope: %f\n', 0.1);
    fprintf(fp, '  }\n');
    fprintf(fp, '}\n');
    
    fprintf(fp, 'layer {\n');
    fprintf(fp, '  name: \"conv4_x\"\n');
    fprintf(fp, '  type: \"Convolution\"\n');
    fprintf(fp, '  bottom: \"conv3_x\"\n');
    fprintf(fp, '  top: \"conv4_x\"\n');
    fprintf(fp, '  param {\n');
    fprintf(fp, '    name: \"conv4_f\"\n');
    fprintf(fp, '    lr_mult: 1\n');
    fprintf(fp, '    decay_mult: 1\n');
    fprintf(fp, '  }\n');
    fprintf(fp, '  param {\n');
    fprintf(fp, '    name: \"conv4_b\"\n');
    fprintf(fp, '    lr_mult: 2\n');
    fprintf(fp, '    decay_mult: 1\n');
    fprintf(fp, '  }\n');
    fprintf(fp, '  convolution_param {\n');
    fprintf(fp, '    num_output: %d\n', 128);
    fprintf(fp, '    kernel_size: %d\n', 3);
    fprintf(fp, '    stride: %d\n', 1);
    fprintf(fp, '    group : %d\n', 1);
    fprintf(fp, '    pad: %d\n', 1);
    fprintf(fp, '    weight_filler {\n');
    fprintf(fp, '      type: \"xavier\"\n');
    fprintf(fp, '    }\n');
    fprintf(fp, '    bias_filler {\n');
    fprintf(fp, '      type: \"constant\"\n');
    fprintf(fp, '      value: 0\n');
    fprintf(fp, '    }\n');
    fprintf(fp, '  }\n');
    fprintf(fp, '}\n');
    
    fprintf(fp, 'layer {\n');
    fprintf(fp, '  name: \"relu4_x\"\n');
    fprintf(fp, '  type: \"ReLU\"\n');
    fprintf(fp, '  bottom: \"conv4_x\"\n');
    fprintf(fp, '  top: \"conv4_x\"\n');
    fprintf(fp, '  relu_param{\n');
    fprintf(fp, '    negative_slope: %f\n', 0.1);
    fprintf(fp, '  }\n');
    fprintf(fp, '}\n');
    
    fprintf(fp, 'layer {\n');
    fprintf(fp, '  name: \"sum2_4_x\"\n');
    fprintf(fp, '  type: \"Eltwise\"\n');
    fprintf(fp, '  bottom: \"conv2_x\"\n');
    fprintf(fp, '  bottom: \"conv4_x\"\n');
    fprintf(fp, '  top: \"sum2_4_x\"\n');
    fprintf(fp, '  eltwise_param { operation: SUM }\n');
    fprintf(fp, '}\n');
    
    fprintf(fp, 'layer {\n');
    fprintf(fp, '  name: \"conv5_x\"\n');
    fprintf(fp, '  type: \"Convolution\"\n');
    fprintf(fp, '  bottom: \"sum2_4_x\"\n');
    fprintf(fp, '  top: \"conv5_x\"\n');
    fprintf(fp, '  param {\n');
    fprintf(fp, '    name: \"conv5_f\"\n');
    fprintf(fp, '    lr_mult: 1\n');
    fprintf(fp, '    decay_mult: 1\n');
    fprintf(fp, '  }\n');
    fprintf(fp, '  param {\n');
    fprintf(fp, '    name: \"conv5_b\"\n');
    fprintf(fp, '    lr_mult: 2\n');
    fprintf(fp, '    decay_mult: 1\n');
    fprintf(fp, '  }\n');
    fprintf(fp, '  convolution_param {\n');
    fprintf(fp, '    num_output: %d\n', 128);
    fprintf(fp, '    kernel_size: %d\n', 3);
    fprintf(fp, '    stride: %d\n', 1);
    fprintf(fp, '    group : %d\n', 1);
    fprintf(fp, '    pad: %d\n', 1);
    fprintf(fp, '    weight_filler {\n');
    fprintf(fp, '      type: \"xavier\"\n');
    fprintf(fp, '    }\n');
    fprintf(fp, '    bias_filler {\n');
    fprintf(fp, '      type: \"constant\"\n');
    fprintf(fp, '      value: 0\n');
    fprintf(fp, '    }\n');
    fprintf(fp, '  }\n');
    fprintf(fp, '}\n');
    
    fprintf(fp, 'layer {\n');
    fprintf(fp, '  name: \"relu5_x\"\n');
    fprintf(fp, '  type: \"ReLU\"\n');
    fprintf(fp, '  bottom: \"conv5_x\"\n');
    fprintf(fp, '  top: \"conv5_x\"\n');
    fprintf(fp, '  relu_param{\n');
    fprintf(fp, '    negative_slope: %f\n', 0.1);
    fprintf(fp, '  }\n');
    fprintf(fp, '}\n');
    
    fprintf(fp, 'layer {\n');
    fprintf(fp, '  name: \"conv6_x\"\n');
    fprintf(fp, '  type: \"Convolution\"\n');
    fprintf(fp, '  bottom: \"conv5_x\"\n');
    fprintf(fp, '  top: \"conv6_x\"\n');
    fprintf(fp, '  param {\n');
    fprintf(fp, '    name: \"conv6_f\"\n');
    fprintf(fp, '    lr_mult: 1\n');
    fprintf(fp, '    decay_mult: 1\n');
    fprintf(fp, '  }\n');
    fprintf(fp, '  param {\n');
    fprintf(fp, '    name: \"conv6_b\"\n');
    fprintf(fp, '    lr_mult: 2\n');
    fprintf(fp, '    decay_mult: 1\n');
    fprintf(fp, '  }\n');
    fprintf(fp, '  convolution_param {\n');
    fprintf(fp, '    num_output: %d\n', 128);
    fprintf(fp, '    kernel_size: %d\n', 3);
    fprintf(fp, '    stride: %d\n', 1);
    fprintf(fp, '    group : %d\n', 1);
    fprintf(fp, '    pad: %d\n', 1);
    fprintf(fp, '    weight_filler {\n');
    fprintf(fp, '      type: \"xavier\"\n');
    fprintf(fp, '    }\n');
    fprintf(fp, '    bias_filler {\n');
    fprintf(fp, '      type: \"constant\"\n');
    fprintf(fp, '      value: 0\n');
    fprintf(fp, '    }\n');
    fprintf(fp, '  }\n');
    fprintf(fp, '}\n');
    
    fprintf(fp, 'layer {\n');
    fprintf(fp, '  name: \"relu6_x\"\n');
    fprintf(fp, '  type: \"ReLU\"\n');
    fprintf(fp, '  bottom: \"conv6_x\"\n');
    fprintf(fp, '  top: \"conv6_x\"\n');
    fprintf(fp, '  relu_param{\n');
    fprintf(fp, '    negative_slope: %f\n', 0.1);
    fprintf(fp, '  }\n');
    fprintf(fp, '}\n');
    
    fprintf(fp, 'layer {\n');
    fprintf(fp, '  name: \"sum4_6_x\"\n');
    fprintf(fp, '  type: \"Eltwise\"\n');
    fprintf(fp, '  bottom: \"sum2_4_x\"\n');
    fprintf(fp, '  bottom: \"conv6_x\"\n');
    fprintf(fp, '  top: \"sum4_6_x\"\n');
    fprintf(fp, '  eltwise_param { operation: SUM }\n');
    fprintf(fp, '}\n');
    
    fprintf(fp, 'layer {\n');
    fprintf(fp, '  name: \"convd7_x\"\n');
    fprintf(fp, '  type: \"Deconvolution\"\n');
    fprintf(fp, '  bottom: \"sum4_6_x\"\n');
    fprintf(fp, '  top: \"convd7_x\"\n');
    fprintf(fp, '  param {\n');
    fprintf(fp, '    name: \"convd7_f\"\n');
    fprintf(fp, '    lr_mult: 1\n');
    fprintf(fp, '    decay_mult: 1\n');
    fprintf(fp, '  }\n');
    fprintf(fp, '  param {\n');
    fprintf(fp, '    name: \"convd7_b\"\n');
    fprintf(fp, '    lr_mult: 2\n');
    fprintf(fp, '    decay_mult: 1\n');
    fprintf(fp, '  }\n');
    fprintf(fp, '  convolution_param {\n');
    fprintf(fp, '    num_output: %d\n', 64);
    fprintf(fp, '    kernel_size: %d\n', 4);
    fprintf(fp, '    stride: %d\n', 2);
    fprintf(fp, '    group : %d\n', 1);
    fprintf(fp, '    pad: %d\n', 1);
    fprintf(fp, '    weight_filler {\n');
    fprintf(fp, '      type: \"bilinear\"\n');
    fprintf(fp, '    }\n');
    fprintf(fp, '  }\n');
    fprintf(fp, '}\n');
    
    fprintf(fp, 'layer {\n');
    fprintf(fp, '  name: \"relu7_x\"\n');
    fprintf(fp, '  type: \"ReLU\"\n');
    fprintf(fp, '  bottom: \"convd7_x\"\n');
    fprintf(fp, '  top: \"convd7_x\"\n');
    fprintf(fp, '  relu_param{\n');
    fprintf(fp, '    negative_slope: %f\n', 0.1);
    fprintf(fp, '  }\n');
    fprintf(fp, '}\n');
    
    fprintf(fp, 'layer {\n');
    fprintf(fp, '  name: \"conv8_x\"\n');
    fprintf(fp, '  type: \"Convolution\"\n');
    fprintf(fp, '  bottom: \"convd7_x\"\n');
    fprintf(fp, '  top: \"conv8_x\"\n');
    fprintf(fp, '  param {\n');
    fprintf(fp, '    name: \"conv8_f\"\n');
    fprintf(fp, '    lr_mult: 1\n');
    fprintf(fp, '    decay_mult: 1\n');
    fprintf(fp, '  }\n');
    fprintf(fp, '  param {\n');
    fprintf(fp, '    name: \"conv8_b\"\n');
    fprintf(fp, '    lr_mult: 2\n');
    fprintf(fp, '    decay_mult: 1\n');
    fprintf(fp, '  }\n');
    fprintf(fp, '  convolution_param {\n');
    fprintf(fp, '    num_output: %d\n', 1);
    fprintf(fp, '    kernel_size: %d\n', 3);
    fprintf(fp, '    stride: %d\n', 1);
    fprintf(fp, '    group : %d\n', 1);
    fprintf(fp, '    pad: %d\n', 1);
    fprintf(fp, '    weight_filler {\n');
    fprintf(fp, '      type: \"xavier\"\n');
    fprintf(fp, '    }\n');
    fprintf(fp, '    bias_filler {\n');
    fprintf(fp, '      type: \"constant\"\n');
    fprintf(fp, '      value: 0\n');
    fprintf(fp, '    }\n');
    fprintf(fp, '  }\n');
    fprintf(fp, '}\n');
    
    fprintf(fp, 'layer {\n');
    fprintf(fp, '  name: \"sum0_8_x\"\n');
    fprintf(fp, '  type: \"Eltwise\"\n');
    fprintf(fp, '  bottom: \"dx\"\n');
    fprintf(fp, '  bottom: \"conv8_x\"\n');
    fprintf(fp, '  top: \"sum0_8_x\"\n');
    fprintf(fp, '  eltwise_param { operation: SUM }\n');
    fprintf(fp, '  loss_weight: 1\n');
    fprintf(fp, '}\n');
    fprintf(fp, '\n');
    
    fprintf(fp, '################## grad y\n');
    
    fprintf(fp, 'layer {\n');
    fprintf(fp, '  name: \"conv1_y\"\n');
    fprintf(fp, '  type: \"Convolution\"\n');
    fprintf(fp, '  bottom: \"dy\"\n');
    fprintf(fp, '  top: \"conv1_y\"\n');
    fprintf(fp, '  param {\n');
    fprintf(fp, '    name: \"conv1_f\"\n');
    fprintf(fp, '    lr_mult: 1\n');
    fprintf(fp, '    decay_mult: 1\n');
    fprintf(fp, '  }\n');
    fprintf(fp, '  param {\n');
    fprintf(fp, '    name: \"conv1_b\"\n');
    fprintf(fp, '    lr_mult: 2\n');
    fprintf(fp, '    decay_mult: 1\n');
    fprintf(fp, '  }\n');
    fprintf(fp, '  convolution_param {\n');
    fprintf(fp, '    num_output: %d\n', 64);
    fprintf(fp, '    kernel_size: %d\n', 9);
    fprintf(fp, '    stride: %d\n', 1);
    fprintf(fp, '    group : %d\n', 1);
    fprintf(fp, '    pad: %d\n', 4);
    fprintf(fp, '    weight_filler {\n');
    fprintf(fp, '      type: \"xavier\"\n');
    fprintf(fp, '    }\n');
    fprintf(fp, '    bias_filler {\n');
    fprintf(fp, '      type: \"constant\"\n');
    fprintf(fp, '      value: 0\n');
    fprintf(fp, '    }\n');
    fprintf(fp, '  }\n');
    fprintf(fp, '}\n');
    
    fprintf(fp, 'layer {\n');
    fprintf(fp, '  name: \"relu1_y\"\n');
    fprintf(fp, '  type: \"ReLU\"\n');
    fprintf(fp, '  bottom: \"conv1_y\"\n');
    fprintf(fp, '  top: \"conv1_y\"\n');
    fprintf(fp, '  relu_param{\n');
    fprintf(fp, '    negative_slope: %f\n', 0.1);
    fprintf(fp, '  }\n');
    fprintf(fp, '}\n');
    
    fprintf(fp, 'layer {\n');
    fprintf(fp, '  name: \"conv2_y\"\n');
    fprintf(fp, '  type: \"Convolution\"\n');
    fprintf(fp, '  bottom: \"conv1_y\"\n');
    fprintf(fp, '  top: \"conv2_y\"\n');
    fprintf(fp, '  param {\n');
    fprintf(fp, '    name: \"conv2_f\"\n');
    fprintf(fp, '    lr_mult: 1\n');
    fprintf(fp, '    decay_mult: 1\n');
    fprintf(fp, '  }\n');
    fprintf(fp, '  param {\n');
    fprintf(fp, '    name: \"conv2_b\"\n');
    fprintf(fp, '    lr_mult: 2\n');
    fprintf(fp, '    decay_mult: 1\n');
    fprintf(fp, '  }\n');
    fprintf(fp, '  convolution_param {\n');
    fprintf(fp, '    num_output: %d\n', 128);
    fprintf(fp, '    kernel_size: %d\n', 3);
    fprintf(fp, '    stride: %d\n', 2);
    fprintf(fp, '    group : %d\n', 1);
    fprintf(fp, '    pad: %d\n', 1);
    fprintf(fp, '    weight_filler {\n');
    fprintf(fp, '      type: \"xavier\"\n');
    fprintf(fp, '    }\n');
    fprintf(fp, '    bias_filler {\n');
    fprintf(fp, '      type: \"constant\"\n');
    fprintf(fp, '      value: 0\n');
    fprintf(fp, '    }\n');
    fprintf(fp, '  }\n');
    fprintf(fp, '}\n');
    
    fprintf(fp, 'layer {\n');
    fprintf(fp, '  name: \"relu2_y\"\n');
    fprintf(fp, '  type: \"ReLU\"\n');
    fprintf(fp, '  bottom: \"conv2_y\"\n');
    fprintf(fp, '  top: \"conv2_y\"\n');
    fprintf(fp, '  relu_param{\n');
    fprintf(fp, '    negative_slope: %f\n', 0.1);
    fprintf(fp, '  }\n');
    fprintf(fp, '}\n');
    
    fprintf(fp, 'layer {\n');
    fprintf(fp, '  name: \"conv3_y\"\n');
    fprintf(fp, '  type: \"Convolution\"\n');
    fprintf(fp, '  bottom: \"conv2_y\"\n');
    fprintf(fp, '  top: \"conv3_y\"\n');
    fprintf(fp, '  param {\n');
    fprintf(fp, '    name: \"conv3_f\"\n');
    fprintf(fp, '    lr_mult: 1\n');
    fprintf(fp, '    decay_mult: 1\n');
    fprintf(fp, '  }\n');
    fprintf(fp, '  param {\n');
    fprintf(fp, '    name: \"conv3_b\"\n');
    fprintf(fp, '    lr_mult: 2\n');
    fprintf(fp, '    decay_mult: 1\n');
    fprintf(fp, '  }\n');
    fprintf(fp, '  convolution_param {\n');
    fprintf(fp, '    num_output: %d\n', 128);
    fprintf(fp, '    kernel_size: %d\n', 3);
    fprintf(fp, '    stride: %d\n', 1);
    fprintf(fp, '    group : %d\n', 1);
    fprintf(fp, '    pad: %d\n', 1);
    fprintf(fp, '    weight_filler {\n');
    fprintf(fp, '      type: \"xavier\"\n');
    fprintf(fp, '    }\n');
    fprintf(fp, '    bias_filler {\n');
    fprintf(fp, '      type: \"constant\"\n');
    fprintf(fp, '      value: 0\n');
    fprintf(fp, '    }\n');
    fprintf(fp, '  }\n');
    fprintf(fp, '}\n');
    
    fprintf(fp, 'layer {\n');
    fprintf(fp, '  name: \"relu3_y\"\n');
    fprintf(fp, '  type: \"ReLU\"\n');
    fprintf(fp, '  bottom: \"conv3_y\"\n');
    fprintf(fp, '  top: \"conv3_y\"\n');
    fprintf(fp, '  relu_param{\n');
    fprintf(fp, '    negative_slope: %f\n', 0.1);
    fprintf(fp, '  }\n');
    fprintf(fp, '}\n');
    
    fprintf(fp, 'layer {\n');
    fprintf(fp, '  name: \"conv4_y\"\n');
    fprintf(fp, '  type: \"Convolution\"\n');
    fprintf(fp, '  bottom: \"conv3_y\"\n');
    fprintf(fp, '  top: \"conv4_y\"\n');
    fprintf(fp, '  param {\n');
    fprintf(fp, '    name: \"conv4_f\"\n');
    fprintf(fp, '    lr_mult: 1\n');
    fprintf(fp, '    decay_mult: 1\n');
    fprintf(fp, '  }\n');
    fprintf(fp, '  param {\n');
    fprintf(fp, '    name: \"conv4_b\"\n');
    fprintf(fp, '    lr_mult: 2\n');
    fprintf(fp, '    decay_mult: 1\n');
    fprintf(fp, '  }\n');
    fprintf(fp, '  convolution_param {\n');
    fprintf(fp, '    num_output: %d\n', 128);
    fprintf(fp, '    kernel_size: %d\n', 3);
    fprintf(fp, '    stride: %d\n', 1);
    fprintf(fp, '    group : %d\n', 1);
    fprintf(fp, '    pad: %d\n', 1);
    fprintf(fp, '    weight_filler {\n');
    fprintf(fp, '      type: \"xavier\"\n');
    fprintf(fp, '    }\n');
    fprintf(fp, '    bias_filler {\n');
    fprintf(fp, '      type: \"constant\"\n');
    fprintf(fp, '      value: 0\n');
    fprintf(fp, '    }\n');
    fprintf(fp, '  }\n');
    fprintf(fp, '}\n');
    
    fprintf(fp, 'layer {\n');
    fprintf(fp, '  name: \"relu4_y\"\n');
    fprintf(fp, '  type: \"ReLU\"\n');
    fprintf(fp, '  bottom: \"conv4_y\"\n');
    fprintf(fp, '  top: \"conv4_y\"\n');
    fprintf(fp, '  relu_param{\n');
    fprintf(fp, '    negative_slope: %f\n', 0.1);
    fprintf(fp, '  }\n');
    fprintf(fp, '}\n');
    
    fprintf(fp, 'layer {\n');
    fprintf(fp, '  name: \"sum2_4_y\"\n');
    fprintf(fp, '  type: \"Eltwise\"\n');
    fprintf(fp, '  bottom: \"conv2_y\"\n');
    fprintf(fp, '  bottom: \"conv4_y\"\n');
    fprintf(fp, '  top: \"sum2_4_y\"\n');
    fprintf(fp, '  eltwise_param { operation: SUM }\n');
    fprintf(fp, '}\n');
    
    fprintf(fp, 'layer {\n');
    fprintf(fp, '  name: \"conv5_y\"\n');
    fprintf(fp, '  type: \"Convolution\"\n');
    fprintf(fp, '  bottom: \"sum2_4_y\"\n');
    fprintf(fp, '  top: \"conv5_y\"\n');
    fprintf(fp, '  param {\n');
    fprintf(fp, '    name: \"conv5_f\"\n');
    fprintf(fp, '    lr_mult: 1\n');
    fprintf(fp, '    decay_mult: 1\n');
    fprintf(fp, '  }\n');
    fprintf(fp, '  param {\n');
    fprintf(fp, '    name: \"conv5_b\"\n');
    fprintf(fp, '    lr_mult: 2\n');
    fprintf(fp, '    decay_mult: 1\n');
    fprintf(fp, '  }\n');
    fprintf(fp, '  convolution_param {\n');
    fprintf(fp, '    num_output: %d\n', 128);
    fprintf(fp, '    kernel_size: %d\n', 3);
    fprintf(fp, '    stride: %d\n', 1);
    fprintf(fp, '    group : %d\n', 1);
    fprintf(fp, '    pad: %d\n', 1);
    fprintf(fp, '    weight_filler {\n');
    fprintf(fp, '      type: \"xavier\"\n');
    fprintf(fp, '    }\n');
    fprintf(fp, '    bias_filler {\n');
    fprintf(fp, '      type: \"constant\"\n');
    fprintf(fp, '      value: 0\n');
    fprintf(fp, '    }\n');
    fprintf(fp, '  }\n');
    fprintf(fp, '}\n');
    
    fprintf(fp, 'layer {\n');
    fprintf(fp, '  name: \"relu5_y\"\n');
    fprintf(fp, '  type: \"ReLU\"\n');
    fprintf(fp, '  bottom: \"conv5_y\"\n');
    fprintf(fp, '  top: \"conv5_y\"\n');
    fprintf(fp, '  relu_param{\n');
    fprintf(fp, '    negative_slope: %f\n', 0.1);
    fprintf(fp, '  }\n');
    fprintf(fp, '}\n');
    
    fprintf(fp, 'layer {\n');
    fprintf(fp, '  name: \"conv6_y\"\n');
    fprintf(fp, '  type: \"Convolution\"\n');
    fprintf(fp, '  bottom: \"conv5_y\"\n');
    fprintf(fp, '  top: \"conv6_y\"\n');
    fprintf(fp, '  param {\n');
    fprintf(fp, '    name: \"conv6_f\"\n');
    fprintf(fp, '    lr_mult: 1\n');
    fprintf(fp, '    decay_mult: 1\n');
    fprintf(fp, '  }\n');
    fprintf(fp, '  param {\n');
    fprintf(fp, '    name: \"conv6_b\"\n');
    fprintf(fp, '    lr_mult: 2\n');
    fprintf(fp, '    decay_mult: 1\n');
    fprintf(fp, '  }\n');
    fprintf(fp, '  convolution_param {\n');
    fprintf(fp, '    num_output: %d\n', 128);
    fprintf(fp, '    kernel_size: %d\n', 3);
    fprintf(fp, '    stride: %d\n', 1);
    fprintf(fp, '    group : %d\n', 1);
    fprintf(fp, '    pad: %d\n', 1);
    fprintf(fp, '    weight_filler {\n');
    fprintf(fp, '      type: \"xavier\"\n');
    fprintf(fp, '    }\n');
    fprintf(fp, '    bias_filler {\n');
    fprintf(fp, '      type: \"constant\"\n');
    fprintf(fp, '      value: 0\n');
    fprintf(fp, '    }\n');
    fprintf(fp, '  }\n');
    fprintf(fp, '}\n');
    
    fprintf(fp, 'layer {\n');
    fprintf(fp, '  name: \"relu6_y\"\n');
    fprintf(fp, '  type: \"ReLU\"\n');
    fprintf(fp, '  bottom: \"conv6_y\"\n');
    fprintf(fp, '  top: \"conv6_y\"\n');
    fprintf(fp, '  relu_param{\n');
    fprintf(fp, '    negative_slope: %f\n', 0.1);
    fprintf(fp, '  }\n');
    fprintf(fp, '}\n');
    
    fprintf(fp, 'layer {\n');
    fprintf(fp, '  name: \"sum4_6_y\"\n');
    fprintf(fp, '  type: \"Eltwise\"\n');
    fprintf(fp, '  bottom: \"sum2_4_y\"\n');
    fprintf(fp, '  bottom: \"conv6_y\"\n');
    fprintf(fp, '  top: \"sum4_6_y\"\n');
    fprintf(fp, '  eltwise_param { operation: SUM }\n');
    fprintf(fp, '}\n');
    
    fprintf(fp, 'layer {\n');
    fprintf(fp, '  name: \"convd7_y\"\n');
    fprintf(fp, '  type: \"Deconvolution\"\n');
    fprintf(fp, '  bottom: \"sum4_6_y\"\n');
    fprintf(fp, '  top: \"convd7_y\"\n');
    fprintf(fp, '  param {\n');
    fprintf(fp, '    name: \"convd7_f\"\n');
    fprintf(fp, '    lr_mult: 1\n');
    fprintf(fp, '    decay_mult: 1\n');
    fprintf(fp, '  }\n');
    fprintf(fp, '  param {\n');
    fprintf(fp, '    name: \"convd7_b\"\n');
    fprintf(fp, '    lr_mult: 2\n');
    fprintf(fp, '    decay_mult: 1\n');
    fprintf(fp, '  }\n');
    fprintf(fp, '  convolution_param {\n');
    fprintf(fp, '    num_output: %d\n', 64);
    fprintf(fp, '    kernel_size: %d\n', 4);
    fprintf(fp, '    stride: %d\n', 2);
    fprintf(fp, '    group : %d\n', 1);
    fprintf(fp, '    pad: %d\n', 1);
    fprintf(fp, '    weight_filler {\n');
    fprintf(fp, '      type: \"bilinear\"\n');
    fprintf(fp, '    }\n');
    fprintf(fp, '  }\n');
    fprintf(fp, '}\n');
    
    fprintf(fp, 'layer {\n');
    fprintf(fp, '  name: \"relu7_y\"\n');
    fprintf(fp, '  type: \"ReLU\"\n');
    fprintf(fp, '  bottom: \"convd7_y\"\n');
    fprintf(fp, '  top: \"convd7_y\"\n');
    fprintf(fp, '  relu_param{\n');
    fprintf(fp, '    negative_slope: %f\n', 0.1);
    fprintf(fp, '  }\n');
    fprintf(fp, '}\n');
    
    fprintf(fp, 'layer {\n');
    fprintf(fp, '  name: \"conv8_y\"\n');
    fprintf(fp, '  type: \"Convolution\"\n');
    fprintf(fp, '  bottom: \"convd7_y\"\n');
    fprintf(fp, '  top: \"conv8_y\"\n');
    fprintf(fp, '  param {\n');
    fprintf(fp, '    name: \"conv8_f\"\n');
    fprintf(fp, '    lr_mult: 1\n');
    fprintf(fp, '    decay_mult: 1\n');
    fprintf(fp, '  }\n');
    fprintf(fp, '  param {\n');
    fprintf(fp, '    name: \"conv8_b\"\n');
    fprintf(fp, '    lr_mult: 2\n');
    fprintf(fp, '    decay_mult: 1\n');
    fprintf(fp, '  }\n');
    fprintf(fp, '  convolution_param {\n');
    fprintf(fp, '    num_output: %d\n', 1);
    fprintf(fp, '    kernel_size: %d\n', 3);
    fprintf(fp, '    stride: %d\n', 1);
    fprintf(fp, '    group : %d\n', 1);
    fprintf(fp, '    pad: %d\n', 1);
    fprintf(fp, '    weight_filler {\n');
    fprintf(fp, '      type: \"xavier\"\n');
    fprintf(fp, '    }\n');
    fprintf(fp, '    bias_filler {\n');
    fprintf(fp, '      type: \"constant\"\n');
    fprintf(fp, '      value: 0\n');
    fprintf(fp, '    }\n');
    fprintf(fp, '  }\n');
    fprintf(fp, '}\n');
    
    fprintf(fp, 'layer {\n');
    fprintf(fp, '  name: \"sum0_8_y\"\n');
    fprintf(fp, '  type: \"Eltwise\"\n');
    fprintf(fp, '  bottom: \"dy\"\n');
    fprintf(fp, '  bottom: \"conv8_y\"\n');
    fprintf(fp, '  top: \"sum0_8_y\"\n');
    fprintf(fp, '  eltwise_param { operation: SUM }\n');
    fprintf(fp, '  loss_weight: 1\n');
    fprintf(fp, '}\n');
    fprintf(fp, '\n');
    
    
    
    
    
    fclose(fp);
end